image: node:6.9.4 # we need node image to run our angular application in 
clone: # help to clone our source here
  depth: full
pipelines: # We set up all the pipeline or actions beneath 
  default: # here most always trigger before any other pipeline 
    - step:
        script:
          - echo "This script runs on all branches that don't have any specific pipeline assigned in 'branches'." 
          
  branches: # This is branch specific configuration, we can set for different branches and different actions when we push codes
  
  
    master:
      - step:
          script: 
            - npm install -g @angular/cli 
            - npm install -g yarn
            - yarn install
            - ng build -prod
            - cd dist
            - git init
            - echo \<?php include_once\(\"index.html\"\)\> > index.php
            - git add -A && git commit -m "base url updated for prod deployment" 
            - git config --global user.email "arothwel@purdue.edu"
            - git config --global user.name "Andrew Rothwell"
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD